export const POKEMONS = {
  GET_DEFAULT_ALL_POKEMONS: 'POKEMONS/GET_DEFAULT_ALL_POKEMONS',
  GET_POKEMON_DETAILS: 'POKEMONS/GET_POKEMON_DETAILS',
  POKEMON_CLEAR_DETAILS: 'POKEMONS/CLEAR_DETAILS',
};
